### PR TITLE
Add custom control option to select

### PR DESCRIPTION
**Pull request by KevinSjoberg**
Add the ability to specify that the given select is a custom control,
adding the necessary classes.

### CODE REVIEW

**Comment by GBH** [comment]
I think it looks good. Please fix the rubocop warning and add an example in the demo gauntlet file: https://github.com/comfy/comfy-bootstrap-form/blob/master/demo/app/views/bootstrap/form.html.erb#L135 Thanks! 👍

**Comment by KevinSjoberg** [comment]
@GBH I've fixed the related Rubocop warnings now. 🙂

**Comment by KevinSjoberg** [comment]
Added select-example in bd62bf6f5c8fff456709a0881d442274251a3d63.

**Comment by GBH** [comment]
Good stuff. Thanks!

**Pull request merged**
